name: YouTube AutoPost

on:
  schedule:
    - cron:  '0 18 * * *' # Elke dag om 18:00
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      # ...andere API-keys

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run automation
        run: |
          python generate_topic.py
          python generate_script.py
          python generate_voiceover.py
          python generate_visuals.py
          python assemble_video.py
          python generate_thumbnail.py
          python upload_to_youtube.py
