name: YouTube AutoPost

on:
  workflow_dispatch:      # Maakt handmatig starten mogelijk via GitHub UI!
  schedule:
    - cron: '0 18 * * *'  # (optioneel) iedere dag om 18:00

jobs:
  autopost:
    runs-on: ubuntu-latest
    env:
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
      YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
      YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Init folders
        run: python init_folders.py
      - name: Run YouTube Automation
        run: |
          python generate_topic.py
          python generate_script.py
          python generate_voiceover.py
          python generate_visuals.py
          python assemble_video.py
          python generate_thumbnail.py
          python upload_to_youtube.py
