name: YouTube Upload Only

on:
  workflow_dispatch:  # handmatig starten

jobs:
  upload_to_youtube:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_CLIENT_SECRET_JSON: ${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}
      YOUTUBE_REFRESH_TOKEN_JSON: ${{ secrets.YOUTUBE_REFRESH_TOKEN_JSON }}

    steps:
      - name: 📥 Repo clonen
        uses: actions/checkout@v4

      - name: 🐍 Python installeren
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Dependencies installeren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔐 Maak client_secret.json
        run: echo '${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}' > client_secret.json

      - name: 🔐 Maak oauth2.json
        run: echo '${{ secrets.YOUTUBE_REFRESH_TOKEN_JSON }}' > oauth2.json

      - name: 🚀 Upload naar YouTube
        run: python upload_to_youtube.py
